import mongoose from 'mongoose';
var User = mongoose.model('User');

var sendJSONresponse = (res, status, content) => {
    res.status(status);
    res.json(content);
};

module.exports.register = (req, res) => {
    //  TODO: allow users to register so they can access protected routes.
    //  Be sure to check all required fields, verify that username is 
    //  unique (send 409 http status code if not).
    //  Send 404 http status code if saving registered user errors out.
    //  A registered user should receive a JWT generated by model/users.js
    sendJSONresponse(res, 400, {
        "message": "All fields required"
    });
};

module.exports.login =  (req, res) => {
    //  TODO: allow registered users to login to access proteted routes.
    //  Be sure to check error cases and return 404/401 http status codes, 
    //  as appropriate. A logged in user should receive a JWT generated 
    //  by model/users.js
    sendJSONresponse(res, 404, new Error("Some error message"));
};