import { NgModule } from '@angular/core';

import {
  MatButtonModule,
  MatButtonToggleModule,
  MatMenuModule,
  MatToolbarModule,
  MatIconModule,
  MatCardModule,
  MatListModule,
  MatFormFieldModule,
  MatSidenavModule,
  MatGridListModule,
  MatSnackBarModule,
  MatSelectModule,
  MatTabsModule,
  MatCheckboxModule,
  MatAutocompleteModule,
  MatDatepickerModule,
  MatRadioModule,
  MatInputModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatProgressBarModule,
  MatDialogModule,
  MatNativeDateModule,
  MatTableModule
} from '@angular/material';

@NgModule({
  imports: [
    MatButtonModule,
    MatButtonToggleModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatListModule,
    MatFormFieldModule,
    MatSidenavModule,
    MatGridListModule,
    MatSnackBarModule,
    MatSelectModule,
    MatTabsModule,
    MatCheckboxModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatRadioModule,
    MatInputModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatProgressBarModule,
    MatDialogModule,
    MatNativeDateModule,
    MatTableModule
  ],
  exports: [
    MatButtonModule,
    MatButtonToggleModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatListModule,
    MatFormFieldModule,
    MatSidenavModule,
    MatGridListModule,
    MatSnackBarModule,
    MatSelectModule,
    MatTabsModule,
    MatCheckboxModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatRadioModule,
    MatInputModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatProgressBarModule,
    MatDialogModule,
    MatNativeDateModule,
    MatTableModule
  ]
})
export class MaterialModule { }
