import { NgModule } from '@angular/core';
import {CdkTableModule} from '@angular/cdk/table';

import {
  MatButtonModule,
  MatButtonToggleModule,
  MatMenuModule,
  MatToolbarModule,
  MatIconModule,
  MatCardModule,
  MatListModule,
  MatFormFieldModule,
  MatSidenavModule,
  MatGridListModule,
  MatSnackBarModule,
  MatSelectModule,
  MatTabsModule,
  MatTableModule,
  MatCheckboxModule,
  MatAutocompleteModule,
  MatDatepickerModule,
  MatNativeDateModule,
  MatPaginatorModule,
  MatRadioModule,
  MatInputModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatProgressBarModule,
  MatDialogModule
} from '@angular/material';

@NgModule({
  imports: [
    CdkTableModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatListModule,
    MatFormFieldModule,
    MatSidenavModule,
    MatGridListModule,
    MatSnackBarModule,
    MatSelectModule,
    MatTabsModule,
    MatTableModule,
    MatCheckboxModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatPaginatorModule,
    MatRadioModule,
    MatInputModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatProgressBarModule,
    MatDialogModule
  ],
  exports: [
    CdkTableModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatMenuModule,
    MatToolbarModule,
    MatIconModule,
    MatCardModule,
    MatListModule,
    MatFormFieldModule,
    MatSidenavModule,
    MatGridListModule,
    MatSnackBarModule,
    MatSelectModule,
    MatTabsModule,
    MatTableModule,
    MatCheckboxModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatNativeDateModule,
    MatPaginatorModule,
    MatRadioModule,
    MatInputModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatProgressBarModule,
    MatDialogModule
  ]
})
export class MaterialModule {}
